structure(list(method = "PUT", url = "https://api/documents/test_document/rollback",
    status_code = 204L, headers = structure(list(Date = "Tue, 08 Oct 2024 17:01:23 GMT",
        Connection = "keep-alive", `X-CONNECT-MDC` = "apiHWNHMifi",
        `X-Frame-Options` = "deny", `X-XSS-Protection` = "1; mode=block",
        `Cache-Control` = "no-cache, no-store", Expires = "0",
        Pragma = "no-cache", `Strict-Transport-Security` = "max-age=31536000 ; includeSubDomains",
        `Content-Security-Policy` = "script-src 'self' 'unsafe-inline'",
        `X-Content-Type-Options` = "nosniff", `Referrer-Policy` = "strict-origin-when-cross-origin",
        `Feature-Policy` = "vibrate 'none'; geolocation 'none'",
        Authorization = "REDACTED", `Set-Cookie` = "REDACTED"), class = "httr2_headers"),
    body = raw(0), cache = new.env(parent = emptyenv())), class = "httr2_response")
