structure(list(method = "PUT", url = "https://api/participants/test_participant/bypassTwoStep",
    status_code = 204L, headers = structure(list(Date = "Mon, 08 Apr 2024 15:26:14 GMT",
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked",
        Connection = "keep-alive", `X-CONNECT-MDC` = "apiblbqkXRf",
        `Referrer-Policy` = "strict-origin-when-cross-origin",
        `Feature-Policy` = "vibrate 'none'; geolocation 'none'",
        `X-Frame-Options` = "deny", `X-XSS-Protection` = "1; mode=block",
        `Cache-Control` = "no-cache, no-store", Expires = "0",
        Pragma = "no-cache", `Strict-Transport-Security` = "max-age=31536000 ; includeSubDomains",
        `Content-Security-Policy` = "script-src 'self' 'unsafe-inline'",
        `X-Content-Type-Options` = "nosniff",
        Authorization = "REDACTED"), class = "httr2_headers"),
    body = raw(0), cache = new.env(parent = emptyenv())), class = "httr2_response")
