structure(list(method = "PUT", url = "https://api/mobileauth/login", 
    status_code = 204L, headers = structure(list(Date = "Fri, 12 Dec 2025 13:20:36 GMT", 
        Connection = "keep-alive", `X-CONNECT-MDC` = "api3da260770c215913fda550168d421521", 
        `X-Frame-Options` = "deny", `X-XSS-Protection` = "1; mode=block", 
        `Cache-Control` = "no-cache, no-store", Expires = "0", 
        Pragma = "no-cache", `Strict-Transport-Security` = "max-age=31536000 ; includeSubDomains", 
        `Content-Security-Policy` = "script-src 'self' 'unsafe-inline'", 
        `X-Content-Type-Options` = "nosniff", `Referrer-Policy` = "strict-origin-when-cross-origin", 
        `Feature-Policy` = "vibrate 'none'; geolocation 'none'", 
        Authorization = "REDACTED", `Set-Cookie` = "REDACTED"), class = "httr2_headers"), 
    body = raw(0), cache = new.env(parent = emptyenv())), class = "httr2_response")
