structure(list(method = "GET", url = "https://api/me", status_code = 200L, 
    headers = structure(list(Date = "Fri, 08 Mar 2024 16:38:49 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "close", `X-CONNECT-MDC` = "apiJrbFTgbE", 
        `X-Frame-Options` = "deny", `X-XSS-Protection` = "1; mode=block", 
        `Cache-Control` = "no-cache, no-store", Expires = "0", 
        Pragma = "no-cache", `Strict-Transport-Security` = "max-age=31536000 ; includeSubDomains", 
        `Content-Security-Policy` = "script-src 'self' 'unsafe-inline'", 
        `X-Content-Type-Options` = "nosniff", `Referrer-Policy` = "strict-origin-when-cross-origin", 
        `Feature-Policy` = "vibrate 'none'; geolocation 'none'", 
        Authorization = "REDACTED", `Set-Cookie` = "REDACTED"), class = "httr2_headers"), 
    body = charToRaw("{\"model\":\"User\",\"uuid\":\"1234\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
